### PR TITLE
Fix incomplete sentence

### PR DESCRIPTION
**Pull request by MaximAbramchuck**

### CODE REVIEW

**Comment by przbadu** [comment]
I try to debug the failing travis-ci, and found this: https://github.com/bundler/bundler/issues/3558. Could you please update latest `bundler version` in CI??

**Comment by przbadu** [comment]
Please take reference from : https://github.com/robertomiranda/has_secure_token/blob/master/.travis.yml, https://github.com/bundler/bundler/issues/3558...to fix failing `travis-ci`

**Comment by MaximAbramchuck** [comment]
@przbadu thanks! you saved a lot of my time!

**Comment by MaximAbramchuck** [comment]
Now will be waiting for @robertomiranda merge

**Comment by robertomiranda** [comment]
thanks you guys :metal:

**Comment by przbadu** [comment]
@MaximAbramchuck: you are welcome, 

@MaximAbramchuck and @robertomiranda : I am stuck in my PR. It would be great if there is nice contribution guide for new feature request in this gem. I am stuck on how to make or where to make PR in rails?? Any Idea??

Reference: [PR-17](https://github.com/robertomiranda/has_secure_token/pull/17)

**Pull request merged**
