### PR TITLE
Generate tokens as per desired length

### PR DESCRIPTION
**Pull request by rohitnick**
Adding token length param to make it customisable as per the application requirement.

### CODE REVIEW

**Comment by rohitnick** [comment]
@robertomiranda : Please have a look at this PR.

**Comment by robertomiranda** [comment]
@rohitnick looks good to me :+1: , could you open this PR at https://github.com/rails/rails?

**Comment by mperrando** [comment]
+1

**Comment by codemnkey** [comment]
+1

When is this merging?

**Comment by rohitnick** [comment]
Couldn't find time to raise a PR at https://github.com/rails/rails as suggest by robertomiranda, will try to raise it soon.

**Comment by fredngo** [comment]
Was a Pull Request ever filed with the main Rails project for this feature?

**Pull request closed without merging**
